# Generated by Django 5.1.4 on 2024-12-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaivariety",
            name="description",
            field=models.TextField(),
        ),
    ]
